Repository TsimpDim/PassBuy, pull requests merged in 2018-06, with the labels that each got.

#91 Fix Toast running on the wrong thread in SearchResults
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/SearchResults.java
Labels: bug

#89 Add and/or improve readme files
  .gitignore
  README.md
Labels: enhancement

#93 categories home button added #86
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/CategoriesSearchPage.java
Labels: feature

#94 Search button fixes #87
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/CategoriesSearchPage.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/SearchResults.java
  front-end/PassBuy/app/src/main/res/layout/categories_search_page.xml
  front-end/PassBuy/app/src/main/res/layout/search_results.xml
Labels: bug, ui

#95 Fixed error handler declaration
  back-end/api/error_handling.js
Labels: enhancement

#96 Places API implementation
  front-end/PassBuy/app/src/main/AndroidManifest.xml
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/Coordinates.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/GsonWorker.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfoActivity.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/StoreLocation.java
Labels: business logic, feature, fundamental

#98 Fix user location tracking
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfoActivity.java
Labels: bug

#103 Fix popup & basket issues
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/CategoriesSearchPage.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/PopupQuantityDialog.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/SearchResults.java
Labels: bug

#104 More Info Functionality
  front-end/PassBuy/app/src/main/AndroidManifest.xml
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/HomeScreen.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfo.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfoAdapter.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/Store.java
  front-end/PassBuy/app/src/main/res/layout/more_info.xml
  front-end/PassBuy/app/src/main/res/layout/more_info_recycler.xml
Labels: feature, fundamental

#105 Basket Info Functionality
  front-end/PassBuy/.idea/caches/build_file_checksums.ser
  front-end/PassBuy/app/src/main/AndroidManifest.xml
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/BasketInfo.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/BasketInfoAdapter.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/Coordinates.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfo.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfoAdapter.java
  front-end/PassBuy/app/src/main/res/layout/basket_info.xml
  front-end/PassBuy/app/src/main/res/layout/basket_info_recycler.xml
Labels: feature, fundamental

#106 Add file load/save system
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/GsonFileWorker.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/HomeScreen.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/SearchResults.java
Labels: feature

#107 General bug fixes
  front-end/PassBuy/app/src/main/AndroidManifest.xml
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/GsonWorker.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/HomeScreen.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfo.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfoAdapter.java
Labels: bug

#109 Make MoreInfo work if user goes online
  front-end/PassBuy/app/src/main/AndroidManifest.xml
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/HomeScreen.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfo.java
Labels: bug

#110 Improve a bit of everything
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/BasketInfo.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/BasketInfoAdapter.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/CategoriesSearchPageAdapter.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/HomeScreen.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/HomeScreenAdapter.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfo.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfoAdapter.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/PopupQuantityDialog.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/SearchResults.java
  front-end/PassBuy/app/src/main/res/layout/categories_search_page.xml
  front-end/PassBuy/app/src/main/res/layout/categories_search_page_recycler.xml
  front-end/PassBuy/app/src/main/res/layout/home_screen.xml
  front-end/PassBuy/app/src/main/res/layout/more_info.xml
  front-end/PassBuy/app/src/main/res/layout/popup_quantity.xml
  front-end/PassBuy/app/src/main/res/layout/search_results.xml
  front-end/PassBuy/app/src/main/res/layout/search_results_recycler.xml
Labels: bug, enhancement

#111 Second cleanup iteration
  front-end/PassBuy/app/src/main/AndroidManifest.xml
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/BasketInfo.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/BasketInfoAdapter.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/CategoriesSearchPage.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/CategoriesSearchPageAdapter.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/GsonFileWorker.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/GsonWorker.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/HomeScreen.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/HomeScreenAdapter.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfo.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/MoreInfoAdapter.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/PopupQuantityDialog.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/SearchResults.java
  front-end/PassBuy/app/src/main/java/thedreamteam/passbuy/SearchResultsAdapter.java
  front-end/PassBuy/app/src/main/res/drawable-hdpi/logo_launcher.png
  front-end/PassBuy/app/src/main/res/drawable-ldpi/logo_launcher.png
  front-end/PassBuy/app/src/main/res/drawable-mdpi/logo_launcher.png
  front-end/PassBuy/app/src/main/res/drawable-xhdpi/logo_launcher.png
  front-end/PassBuy/app/src/main/res/drawable-xxhdpi/logo_launcher.png
  front-end/PassBuy/app/src/main/res/drawable-xxxhdpi/logo_launcher.png
  front-end/PassBuy/app/src/main/res/layout/categories_search_page_recycler.xml
  front-end/PassBuy/app/src/main/res/layout/more_info.xml
Labels: enhancement

#114 Minor UI fix
  front-end/PassBuy/app/src/main/res/layout/home_screen.xml
Labels: bug
